version: '2'
services:
    staceyeditor-app:
        image: staceyeditor
        external_links:
            - staceyeditor-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/staceyEditor
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    staceyeditor-postgresql:
        extends:
            file: postgresql.yml
            service: staceyeditor-postgresql
